-define(INCORRECT_FORMAT, <<"Data has an incorrect format">>).
-define(NO_SOLUTION, <<"No solutions found">>).
-define(NO_SEQUENCE, <<"The sequence isn\'t found">>).
-define(NOT_ENOUGH_DATA, <<"There isn\'t enough data">>).
-define(ALREADY_STOPPED, <<"The red observation should be the last">>).
